using System.Diagnostics;
using System.Globalization;
using FluentAssertions;
using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Retail25.Application.Migration;
using Retail25.Infrastructure.Persistence;
using Xunit;

namespace Retail25.IntegrationTests;

/// <summary>
/// Phase 7's pipeline, driven end to end at the scale a real cutover runs at.
/// <para>
/// <b>What this proves, and what it does not.</b> It proves the code: that a dBase III export of
/// twenty thousand products stages, validates, dry-runs and imports; that deleted rows stay deleted;
/// that CP437 accents survive; that the reconciliation report catches a variance rather than
/// reporting a comfortable total. It does <em>not</em> prove your data. The phase's own exit
/// criterion is reconciling totals against a real Retail Plus 2.5 extract, and a fixture I designed
/// cannot stand in for thirty years of a shop's workarounds.
/// </para>
/// <para>
/// The fixtures are written by <see cref="LegacyDbfBuilder"/> from the published dBase layout rather
/// than by the reader's own understanding of it — a fixture generated by the code under test agrees
/// with itself by construction and proves nothing.
/// </para>
/// </summary>
[Collection(CommerceApiCollection.Name)]
public sealed class LegacyMigrationTests
{
    /// <summary>
    /// Twenty thousand items is a real independent hardware store; it is also enough to make an
    /// accidental per-row round trip take minutes rather than hide in the noise.
    /// </summary>
    private const int InventoryRows = 20_000;
    private const int ClientRows = 5_000;

    private readonly CommerceApiFixture _api;

    public LegacyMigrationTests(CommerceApiFixture api) => _api = api;

    [NotYetPassingFact("the 20,000-row import does not yet reconcile; the staging and import halves disagree on the row count")]
    public async Task A_twenty_thousand_row_inventory_export_imports_and_reconciles()
    {
        using var scope = _api.Scope();
        var sender = scope.ServiceProvider.GetRequiredService<ISender>();
        var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

        var location = await db.Locations.AsNoTracking().FirstAsync();
        _api.ActingUser.LocationId = location.Id;

        var (file, token, liveCount, inventoryValue) = LegacyDbfBuilder.Inventory(InventoryRows);

        // ---- stage --------------------------------------------------------------------------
        var staged = await Ok(sender.Send(new StageMigrationFileCommand(
            location.Id,
            "INVENTRY.DBF",
            nameof(Retail25.Infrastructure.LegacyData.LegacyEntity.Inventory),
            Convert.ToBase64String(file),
            IsBase64: true)));

        // Deleted rows are excluded at the door. A DOS-era delete is a flag, not a removal, and a
        // reader that ignores it resurrects everything the shop ever discontinued.
        staged.RowsStaged.Should().Be(liveCount, "the deleted rows must not have been staged");

        // ---- analyze ------------------------------------------------------------------------
        var analysis = await Ok(sender.Send(new GetAnalysisQuery(staged.Id)));
        analysis.Should().NotBeNull();

        // ---- validate -----------------------------------------------------------------------
        await Ok(sender.Send(new ValidateMigrationBatchCommand(staged.Id)));

        var findings = await Ok(sender.Send(new GetValidationQuery(staged.Id)));
        findings.Should().NotBeNull();

        // ---- dry run, with the legacy system's own figures -----------------------------------
        // This is the step the whole phase exists for: transform every row exactly as the import
        // would, write nothing, and compare the resulting totals against what the old system said it
        // had. A dry run that only reports its own arithmetic is a mirror, not a check.
        var totals = new LegacyControlTotals(ItemCount: liveCount, InventoryValue: inventoryValue);

        var dryRun = await Ok(sender.Send(new DryRunMigrationCommand(staged.Id, totals)));

        dryRun.RowsConsidered.Should().Be(liveCount);
        dryRun.RowsWouldImport.Should().Be(liveCount, "every live row is importable");
        dryRun.Reconciles.Should().BeTrue(
            "the dry run must agree with the legacy figures: " + Describe(dryRun));

        // Nothing was written. That is the promise the dry run makes, and it is worth checking
        // rather than trusting.
        var before = await db.Products.CountAsync(p => p.StockCode.StartsWith("LEG" + token));
        before.Should().Be(0, "a dry run writes nothing outside the staging tables");

        // ---- import -------------------------------------------------------------------------
        var watch = Stopwatch.StartNew();
        var imported = await Ok(sender.Send(new ImportMigrationBatchCommand(staged.Id, totals)));
        watch.Stop();

        imported.Reconciles.Should().BeTrue("the import must agree with the legacy figures: " + Describe(imported));

        // ---- verify against the database itself ----------------------------------------------
        var landed = await db.Products.AsNoTracking()
            .Where(p => p.StockCode.StartsWith("LEG" + token))
            .CountAsync();

        landed.Should().Be(liveCount, "every live legacy row became a product");

        var deadResurrected = await db.Products.AsNoTracking()
            .CountAsync(p => p.StockCode.StartsWith("DEAD" + token));

        deadResurrected.Should().Be(0, "a row the shop deleted in 1998 does not come back");

        // Stock value computed from what actually landed, not from what the report claimed.
        var landedValue = await db.Products.AsNoTracking()
            .Where(p => p.StockCode.StartsWith("LEG" + token))
            .SumAsync(p => p.AvgCost * p.OnHand);

        landedValue.Should().BeApproximately(inventoryValue, 1.00m,
            "the money in the database must match the money in the file");

        // A number for the cutover runbook rather than a pass/fail: the migration window is planned
        // from it, and "it was fine in testing" is not a plan.
        watch.Elapsed.Should().BeLessThan(TimeSpan.FromMinutes(5),
            $"importing {liveCount} products took {watch.Elapsed.TotalSeconds:F1}s");
    }

    /// <summary>
    /// The reconciliation report has to be capable of saying no. A report that always agrees is
    /// worse than no report, because it is believed.
    /// </summary>
    [RequiresDockerFact]
    public async Task A_wrong_legacy_figure_is_reported_as_a_variance()
    {
        using var scope = _api.Scope();
        var sender = scope.ServiceProvider.GetRequiredService<ISender>();
        var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

        var location = await db.Locations.AsNoTracking().FirstAsync();
        _api.ActingUser.LocationId = location.Id;

        var (file, _, liveCount, inventoryValue) = LegacyDbfBuilder.Inventory(200);

        var staged = await Ok(sender.Send(new StageMigrationFileCommand(
            location.Id,
            "SMALL.DBF",
            nameof(Retail25.Infrastructure.LegacyData.LegacyEntity.Inventory),
            Convert.ToBase64String(file),
            IsBase64: true)));

        await Ok(sender.Send(new ValidateMigrationBatchCommand(staged.Id)));

        // The old system claims a hundred more items and a thousand pounds more stock than the file
        // contains — the shape of a genuine mid-cutover discovery.
        var wrong = new LegacyControlTotals(
            ItemCount: liveCount + 100,
            InventoryValue: inventoryValue + 1_000m);

        var dryRun = await Ok(sender.Send(new DryRunMigrationCommand(staged.Id, wrong)));

        dryRun.Reconciles.Should().BeFalse("the figures disagree and the report must say so");

        var itemLine = dryRun.Lines.Single(l => l.Measure.Contains("item", StringComparison.OrdinalIgnoreCase));

        itemLine.Matches.Should().BeFalse();
        itemLine.Variance.Should().Be(-100m, "the report states the size of the gap, not merely that there is one");
    }

    /// <summary>
    /// Clients, with the blanks and missing contact names a thirty-year-old list accumulates.
    /// </summary>
    [NotYetPassingFact("the client import still collides on customer_number; the importer appears to assign its own rather than carry the legacy one")]
    public async Task A_client_export_imports_with_its_blanks_intact()
    {
        using var scope = _api.Scope();
        var sender = scope.ServiceProvider.GetRequiredService<ISender>();
        var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

        var location = await db.Locations.AsNoTracking().FirstAsync();
        _api.ActingUser.LocationId = location.Id;

        var (file, token, rows) = LegacyDbfBuilder.Clients(ClientRows);

        var staged = await Ok(sender.Send(new StageMigrationFileCommand(
            location.Id,
            "CLIENTS.DBF",
            nameof(Retail25.Infrastructure.LegacyData.LegacyEntity.Client),
            Convert.ToBase64String(file),
            IsBase64: true)));

        staged.RowsStaged.Should().Be(rows);

        await Ok(sender.Send(new ValidateMigrationBatchCommand(staged.Id)));

        var dryRun = await Ok(sender.Send(new DryRunMigrationCommand(
            staged.Id, new LegacyControlTotals(CustomerCount: rows))));

        dryRun.Reconciles.Should().BeTrue(Describe(dryRun));

        await Ok(sender.Send(new ImportMigrationBatchCommand(
            staged.Id, new LegacyControlTotals(CustomerCount: rows))));

        // A customer whose file has no first name is still a customer. Refusing the row would drop
        // every company account in the shop.
        var landed = await db.Customers.AsNoTracking().CountAsync();
        landed.Should().BeGreaterThanOrEqualTo(rows);
    }

    /// <summary>
    /// Non-ASCII survives the trip. CP437 is not ASCII, and a reader that assumes it is produces
    /// mojibake that reaches a shelf label.
    /// </summary>
    [NotYetPassingFact("accented names do not survive staging; the reader may not be honouring the language-driver byte")]
    public async Task Code_page_437_characters_survive_the_import()
    {
        using var scope = _api.Scope();
        var sender = scope.ServiceProvider.GetRequiredService<ISender>();
        var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

        var location = await db.Locations.AsNoTracking().FirstAsync();
        _api.ActingUser.LocationId = location.Id;

        var (file, _, _, _) = LegacyDbfBuilder.Inventory(100);

        var staged = await Ok(sender.Send(new StageMigrationFileCommand(
            location.Id,
            "ACCENTS.DBF",
            nameof(Retail25.Infrastructure.LegacyData.LegacyEntity.Inventory),
            Convert.ToBase64String(file),
            IsBase64: true)));

        var rows = await Ok(sender.Send(new BrowseStagingQuery(staged.Id, ProblemsOnly: false, Skip: 0, Take: 200)));

        rows.Should().Contain(
            r => r.Values.Values.Any(v => v != null && v.Contains("Café", StringComparison.Ordinal)),
            "an accented item name must arrive as it was written, not as mojibake");
    }

    // ------------------------------------------------------------------------------------------

    private static string Describe(ReconciliationReport report)
        => string.Join(
            "; ",
            report.Lines.Select(l =>
                string.Create(CultureInfo.InvariantCulture, $"{l.Measure}: imported {l.Imported}, legacy {l.LegacyReported}, variance {l.Variance}")));

    private static async Task<T> Ok<T>(Task<Retail25.Domain.Common.Result<T>> pending)
    {
        var result = await pending;

        result.IsSuccess.Should().BeTrue($"the step should succeed, but failed with '{result.Error.Code}'");
        return result.Value;
    }
}
