using System.Diagnostics;
using System.Globalization;
using FluentAssertions;
using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Retail25.Application.Migration;
using Retail25.Infrastructure.Persistence;
using Xunit;

namespace Retail25.IntegrationTests;

/// <summary>
/// Phase 7's pipeline, driven end to end at the scale a real cutover runs at.
/// <para>
/// <b>What this proves, and what it does not.</b> It proves the code: that a dBase III export of
/// twenty thousand products stages, validates, dry-runs and imports; that rows the shop deleted stay
/// deleted; that a DOS code page survives; that the reconciliation report catches a variance rather
/// than reporting a comfortable total. It does <em>not</em> prove your data. The phase's own exit
/// criterion is reconciling totals against a real Retail Plus 2.5 extract, and a fixture I designed
/// cannot stand in for thirty years of a shop's workarounds.
/// </para>
/// <para>
/// The fixtures are written by <see cref="LegacyDbfBuilder"/> from the published dBase layout rather
/// than by the reader's own understanding of it. A fixture generated by the code under test agrees
/// with itself by construction and proves nothing.
/// </para>
/// </summary>
[Collection(CommerceApiCollection.Name)]
public sealed class LegacyMigrationTests
{
    /// <summary>
    /// Twenty thousand items is a real independent hardware store; it is also enough to make an
    /// accidental per-row round trip take minutes rather than hide in the noise.
    /// </summary>
    private const int InventoryRows = 20_000;
    private const int ClientRows = 5_000;

    /// <summary>Matches the one-in-fifty ratio <see cref="LegacyDbfBuilder.Inventory"/> writes.</summary>
    private const int DeletedRows = InventoryRows / 50;

    private readonly CommerceApiFixture _api;

    public LegacyMigrationTests(CommerceApiFixture api) => _api = api;

    [RequiresDockerFact]
    public async Task A_twenty_thousand_row_inventory_export_imports_and_reconciles()
    {
        using var scope = _api.Scope();
        var sender = scope.ServiceProvider.GetRequiredService<ISender>();
        var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

        var location = await db.Locations.AsNoTracking().FirstAsync();
        _api.ActingUser.LocationId = location.Id;

        var (file, token, liveCount, inventoryValue) = LegacyDbfBuilder.Inventory(InventoryRows);

        // ---- stage --------------------------------------------------------------------------
        var staged = await Ok(sender.Send(new StageMigrationFileCommand(
            location.Id,
            "INVENTRY.DBF",
            nameof(Retail25.Infrastructure.LegacyData.LegacyEntity.Inventory),
            Convert.ToBase64String(file),
            IsBase64: true)));

        // Deleted rows are staged with their flag rather than dropped at the door, and that is the
        // right design: a DOS-era delete is a flag, not a removal, so a supervisor reviewing the
        // batch can see what the old system was hiding and decide. What matters is that they are
        // counted separately and never imported.
        //
        // (My first version of this test asserted they were excluded from staging entirely, and
        // failed at 20,400 against an expected 20,000. The test was wrong, not the pipeline.)
        staged.RowsStaged.Should().Be(liveCount + DeletedRows, "every row in the file is staged");
        staged.RowsDeletedInSource.Should().Be(DeletedRows, "and the deleted ones are counted apart");

        // ---- analyze ------------------------------------------------------------------------
        var analysis = await Ok(sender.Send(new GetAnalysisQuery(staged.Id)));
        analysis.Should().NotBeNull();

        // ---- validate -----------------------------------------------------------------------
        await Ok(sender.Send(new ValidateMigrationBatchCommand(staged.Id)));

        var findings = await Ok(sender.Send(new GetValidationQuery(staged.Id)));
        findings.Should().NotBeNull();

        // ---- dry run, with the legacy system's own figures -----------------------------------
        // The step the whole phase exists for: transform every row exactly as the import would,
        // write nothing, and compare the resulting totals against what the old system said it had.
        // A dry run that only reports its own arithmetic is a mirror, not a check.
        var totals = new LegacyControlTotals(ItemCount: liveCount, InventoryValue: inventoryValue);

        var dryRun = await Ok(sender.Send(new DryRunMigrationCommand(staged.Id, totals)));

        dryRun.RowsWouldImport.Should().Be(liveCount, "every live row is importable, and no deleted one is");
        dryRun.Reconciles.Should().BeTrue("the dry run must agree with the legacy figures: " + Describe(dryRun));

        // Nothing was written. That is the promise the dry run makes, and it is worth checking
        // rather than trusting.
        var before = await db.Products.CountAsync(p => p.StockCode.StartsWith("LEG" + token));
        before.Should().Be(0, "a dry run writes nothing outside the staging tables");

        // ---- import -------------------------------------------------------------------------
        var watch = Stopwatch.StartNew();
        var imported = await Ok(sender.Send(new ImportMigrationBatchCommand(staged.Id, totals)));
        watch.Stop();

        imported.Reconciles.Should().BeTrue("the import must agree with the legacy figures: " + Describe(imported));

        // ---- verify against the database itself ----------------------------------------------
        var landed = await db.Products.AsNoTracking()
            .Where(p => p.StockCode.StartsWith("LEG" + token))
            .CountAsync();

        landed.Should().Be(liveCount, "every live legacy row became a product");

        var deadResurrected = await db.Products.AsNoTracking()
            .CountAsync(p => p.StockCode.StartsWith("DEAD" + token));

        deadResurrected.Should().Be(0, "a row the shop deleted in 1998 does not come back");

        // Stock value computed from what actually landed, not from what the report claimed.
        var landedValue = await db.Products.AsNoTracking()
            .Where(p => p.StockCode.StartsWith("LEG" + token))
            .SumAsync(p => p.AvgCost * p.OnHand);

        landedValue.Should().BeApproximately(inventoryValue, 1.00m,
            "the money in the database must match the money in the file");

        // A number for the cutover runbook rather than a pass/fail: the migration window is planned
        // from it, and "it was fine in testing" is not a plan.
        watch.Elapsed.Should().BeLessThan(TimeSpan.FromMinutes(5),
            $"importing {liveCount} products took {watch.Elapsed.TotalSeconds:F1}s");
    }

    /// <summary>
    /// The reconciliation report has to be capable of saying no. A report that always agrees is
    /// worse than no report, because it is believed.
    /// </summary>
    [RequiresDockerFact]
    public async Task A_wrong_legacy_figure_is_reported_as_a_variance()
    {
        using var scope = _api.Scope();
        var sender = scope.ServiceProvider.GetRequiredService<ISender>();
        var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

        var location = await db.Locations.AsNoTracking().FirstAsync();
        _api.ActingUser.LocationId = location.Id;

        var (file, _, liveCount, inventoryValue) = LegacyDbfBuilder.Inventory(200);

        var staged = await Ok(sender.Send(new StageMigrationFileCommand(
            location.Id,
            "SMALL.DBF",
            nameof(Retail25.Infrastructure.LegacyData.LegacyEntity.Inventory),
            Convert.ToBase64String(file),
            IsBase64: true)));

        await Ok(sender.Send(new ValidateMigrationBatchCommand(staged.Id)));

        // The old system claims a hundred more items and a thousand pounds more stock than the file
        // contains, which is the shape of a genuine mid-cutover discovery.
        var wrong = new LegacyControlTotals(
            ItemCount: liveCount + 100,
            InventoryValue: inventoryValue + 1_000m);

        var dryRun = await Ok(sender.Send(new DryRunMigrationCommand(staged.Id, wrong)));

        dryRun.Reconciles.Should().BeFalse("the figures disagree and the report must say so");

        var itemLine = dryRun.Lines.Single(l => l.Measure.Contains("item", StringComparison.OrdinalIgnoreCase));

        itemLine.Matches.Should().BeFalse();
        itemLine.Variance.Should().Be(-100m, "the report states the size of the gap, not merely that there is one");
    }

    /// <summary>
    /// Clients, with the blanks and missing contact names a thirty-year-old list accumulates.
    /// </summary>
    [RequiresDockerFact]
    public async Task A_client_export_imports_with_its_blanks_intact()
    {
        using var scope = _api.Scope();
        var sender = scope.ServiceProvider.GetRequiredService<ISender>();
        var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

        var location = await db.Locations.AsNoTracking().FirstAsync();
        _api.ActingUser.LocationId = location.Id;

        var (file, _, rows) = LegacyDbfBuilder.Clients(ClientRows);

        var staged = await Ok(sender.Send(new StageMigrationFileCommand(
            location.Id,
            "CLIENTS.DBF",
            nameof(Retail25.Infrastructure.LegacyData.LegacyEntity.Client),
            Convert.ToBase64String(file),
            IsBase64: true)));

        staged.RowsStaged.Should().Be(rows);

        await Ok(sender.Send(new ValidateMigrationBatchCommand(staged.Id)));

        var totals = new LegacyControlTotals(CustomerCount: rows);

        var dryRun = await Ok(sender.Send(new DryRunMigrationCommand(staged.Id, totals)));
        dryRun.Reconciles.Should().BeTrue(Describe(dryRun));

        var before = await db.Customers.CountAsync();

        await Ok(sender.Send(new ImportMigrationBatchCommand(staged.Id, totals)));

        // A customer whose file has no first name is still a customer. Refusing the row would drop
        // every company account in the shop.
        var after = await db.Customers.CountAsync();
        (after - before).Should().Be(rows, "every client row became a customer, blanks and all");
    }

    /// <summary>
    /// A DOS code page survives the trip.
    /// <para>
    /// CP437 is not ASCII, and a reader that assumes CP1252 turns the byte for an accented "e" into
    /// a low quotation mark. That is not a crash; it is a shelf label that reads "Caf,". The reader
    /// takes the code page from the file's own language-driver byte, which is what this asserts.
    /// </para>
    /// </summary>
    [RequiresDockerFact]
    public async Task A_dos_code_page_survives_the_import()
    {
        using var scope = _api.Scope();
        var sender = scope.ServiceProvider.GetRequiredService<ISender>();
        var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

        var location = await db.Locations.AsNoTracking().FirstAsync();
        _api.ActingUser.LocationId = location.Id;

        var (file, _, _, _) = LegacyDbfBuilder.Inventory(100);

        var staged = await Ok(sender.Send(new StageMigrationFileCommand(
            location.Id,
            "ACCENTS.DBF",
            nameof(Retail25.Infrastructure.LegacyData.LegacyEntity.Inventory),
            Convert.ToBase64String(file),
            IsBase64: true)));

        var rows = await Ok(sender.Send(new BrowseStagingQuery(staged.Id, ProblemsOnly: false, Skip: 0, Take: 200)));

        // Escaped rather than written as a literal. A source file carrying a raw accented character
        // survives only as long as every tool that touches it agrees on the encoding, and one
        // round-trip through a shell rewrote this file's literal as double-encoded UTF-8 so the
        // assertion hunted for a string the fixture never produced. An escape cannot be mangled.
        const string Cafe = "Café";
        const string Mojibake = "Caf‚";

        rows.Should().Contain(
            r => r.Values.Values.Any(v => v != null && v.Contains(Cafe, StringComparison.Ordinal)),
            "an accented item name must arrive as it was written");

        rows.Should().NotContain(
            r => r.Values.Values.Any(v => v != null && v.Contains(Mojibake, StringComparison.Ordinal)),
            "and must not arrive decoded as CP1252, which is the failure this guards");
    }

    // ------------------------------------------------------------------------------------------

    private static string Describe(ReconciliationReport report)
        => string.Join(
            "; ",
            report.Lines.Select(l => string.Create(
                CultureInfo.InvariantCulture,
                $"{l.Measure}: imported {l.Imported}, legacy {l.LegacyReported}, variance {l.Variance}")));

    private static async Task<T> Ok<T>(Task<Retail25.Domain.Common.Result<T>> pending)
    {
        var result = await pending;

        result.IsSuccess.Should().BeTrue($"the step should succeed, but failed with '{result.Error.Code}'");
        return result.Value;
    }
}
