using Microsoft.EntityFrameworkCore;
using NSubstitute;
using Retail25.Application.Abstractions;
using Retail25.Infrastructure.Persistence;
using Testcontainers.PostgreSql;
using Xunit;

namespace Retail25.IntegrationTests;

/// <summary>
/// A real PostgreSQL 16 for the tests that cannot be answered without one.
/// <para>
/// The unit suites run against the in-memory provider, which is the right trade for handler
/// behaviour but is silent about two whole classes of defect: a LINQ expression that cannot be
/// translated to SQL (it just runs client-side instead), and anything to do with the actual schema —
/// value converters, owned types, constraints, sequences. Both have already produced bugs in this
/// codebase that the unit tests passed straight through.
/// </para>
/// <para>
/// One container for the whole collection, because starting Postgres costs seconds and the tests
/// here do not need isolation from each other — each seeds the rows it asserts on.
/// </para>
/// </summary>
public sealed class PostgresFixture : IAsyncLifetime
{
    private readonly PostgreSqlContainer _container = new PostgreSqlBuilder()
        .WithImage("postgres:16-alpine")
        .WithDatabase("retail25_tests")
        .WithUsername("retail25")
        .WithPassword("retail25")
        .Build();

    public string ConnectionString => _container.GetConnectionString();

    /// <summary>
    /// Starts the container only when a daemon is there to start it on. Without this the fixture
    /// throws during collection setup and every test in the collection reports as failed rather than
    /// skipped, which is the wrong answer to "you do not have Docker running".
    /// </summary>
    public async Task InitializeAsync()
    {
        if (DockerProbe.IsAvailable)
        {
            await _container.StartAsync();
        }
    }

    public async Task DisposeAsync()
    {
        if (DockerProbe.IsAvailable)
        {
            await _container.DisposeAsync();
        }
    }

    /// <summary>
    /// A context wired exactly as the application wires it — same naming convention, same migrations
    /// assembly, same auditing interceptor. A fixture that configured it differently would prove
    /// something about the fixture rather than about the system.
    /// </summary>
    public ApplicationDbContext CreateContext(string? connectionString = null)
    {
        var clock = Substitute.For<IDateTime>();
        clock.Now.Returns(new DateTimeOffset(2026, 7, 29, 10, 0, 0, TimeSpan.Zero));

        var currentUser = Substitute.For<ICurrentUser>();
        currentUser.UserId.Returns(Guid.NewGuid());

        var interceptor = new AuditingInterceptor(currentUser, Substitute.For<IRequestContext>(), clock);

        var options = new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseNpgsql(
                connectionString ?? ConnectionString,
                npgsql => npgsql.MigrationsAssembly(typeof(ApplicationDbContext).Assembly.FullName))
            .UseSnakeCaseNamingConvention()
            .AddInterceptors(interceptor)
            .Options;

        return new ApplicationDbContext(options);
    }

    /// <summary>
    /// Creates an empty database on the running server and returns its connection string, so a test
    /// can prove something about a database nothing has touched yet.
    /// </summary>
    public async Task<string> CreateEmptyDatabaseAsync(string name)
    {
        await using var admin = CreateContext();

#pragma warning disable EF1002 // The name is generated by the caller from a test method name.
        await admin.Database.ExecuteSqlRawAsync($"DROP DATABASE IF EXISTS \"{name}\" WITH (FORCE)");
        await admin.Database.ExecuteSqlRawAsync($"CREATE DATABASE \"{name}\"");
#pragma warning restore EF1002

        var builder = new Npgsql.NpgsqlConnectionStringBuilder(ConnectionString) { Database = name };
        return builder.ConnectionString;
    }
}

[CollectionDefinition(Name)]
public sealed class PostgresCollection : ICollectionFixture<PostgresFixture>
{
    public const string Name = "postgres";
}
