CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

CREATE TABLE ar_ledger_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    customer_id bigint NOT NULL,
    invoice_id bigint NOT NULL,
    entry_type integer NOT NULL,
    amount numeric NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_ar_ledger_entries PRIMARY KEY (id)
);

CREATE TABLE "AspNetRoles" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    legacy_level integer,
    description text,
    name character varying(256),
    normalized_name character varying(256),
    concurrency_stamp text,
    CONSTRAINT pk_asp_net_roles PRIMARY KEY (id)
);

CREATE TABLE "AspNetUsers" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    display_name text NOT NULL,
    is_enabled boolean NOT NULL,
    default_location_id bigint,
    last_signed_in_at timestamp with time zone,
    user_name character varying(256),
    normalized_user_name character varying(256),
    email character varying(256),
    normalized_email character varying(256),
    email_confirmed boolean NOT NULL,
    password_hash text,
    security_stamp text,
    concurrency_stamp text,
    phone_number text,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    CONSTRAINT pk_asp_net_users PRIMARY KEY (id)
);

CREATE TABLE audit_log_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    occurred_at timestamp with time zone NOT NULL,
    action character varying(24) NOT NULL,
    actor_user_id bigint,
    actor_staff_id bigint,
    actor_name character varying(200),
    station_id bigint,
    location_id bigint,
    ip_address character varying(64),
    entity_type character varying(80) NOT NULL,
    entity_id character varying(64),
    operation character varying(120),
    before_json jsonb,
    after_json jsonb,
    correlation_id character varying(128),
    approver_staff_id bigint,
    reason character varying(500),
    row_version bigint NOT NULL,
    CONSTRAINT pk_audit_log_entries PRIMARY KEY (id)
);

CREATE TABLE bonus_pricings (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    buy_qty numeric NOT NULL,
    free_qty numeric NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_bonus_pricings PRIMARY KEY (id)
);

CREATE TABLE business_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    business_name character varying(200) NOT NULL,
    address_line1 character varying(200),
    address_line2 character varying(200),
    address_city character varying(100),
    address_state_or_province character varying(100),
    address_postal_code character varying(20),
    address_country character varying(100),
    contact_phone character varying(30),
    contact_extension character varying(10),
    contact_mobile character varying(30),
    contact_fax character varying(30),
    contact_email character varying(200),
    contact_website character varying(200),
    licence_number character varying(60),
    tax_registration_number character varying(40),
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_business_profiles PRIMARY KEY (id)
);

CREATE TABLE cart_adjustments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    cart_id bigint NOT NULL,
    type character varying(24) NOT NULL,
    label character varying(120) NOT NULL,
    amount numeric(19,4) NOT NULL,
    percent numeric(7,2) NOT NULL,
    serial character varying(64),
    applied_by_staff_id bigint NOT NULL,
    applied_at timestamp with time zone NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_cart_adjustments PRIMARY KEY (id)
);

CREATE TABLE cart_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    cart_id bigint NOT NULL,
    product_id bigint NOT NULL,
    variant_id bigint,
    serialized_unit_id bigint,
    epc text,
    source character varying(20) NOT NULL,
    quantity numeric(18,4) NOT NULL,
    manual_unit_price numeric,
    manual_discount_pct numeric,
    requested_price_level integer,
    tax1override boolean,
    tax2override boolean,
    embedded_price numeric,
    line_type character varying(20) NOT NULL,
    return_to_stock boolean NOT NULL,
    note text,
    sequence integer NOT NULL,
    unit_price numeric(19,4) NOT NULL,
    price_origin character varying(20) NOT NULL,
    line_discount_pct numeric(7,2) NOT NULL,
    tax1applies boolean NOT NULL,
    tax2applies boolean NOT NULL,
    extended_net numeric NOT NULL,
    tax1amount numeric NOT NULL,
    tax2amount numeric NOT NULL,
    stock_code_snapshot character varying(24),
    name_snapshot character varying(200),
    unit_cost_snapshot numeric(19,3) NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_cart_lines PRIMARY KEY (id)
);

CREATE TABLE cart_tax_overrides (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    cart_id bigint NOT NULL,
    tax1 boolean,
    tax2 boolean,
    applies_from_sequence integer NOT NULL,
    applied_by_staff_id bigint NOT NULL,
    applied_at timestamp with time zone NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_cart_tax_overrides PRIMARY KEY (id)
);

CREATE TABLE carts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    station_id bigint NOT NULL,
    location_id bigint NOT NULL,
    staff_id bigint NOT NULL,
    customer_id bigint,
    status character varying(20) NOT NULL,
    held_name character varying(100),
    suspended_at timestamp with time zone,
    suspended_by_staff_id bigint,
    next_line_sequence integer NOT NULL,
    revision integer NOT NULL,
    completed_transaction_id bigint,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    expires_at timestamp with time zone,
    row_version bigint NOT NULL,
    CONSTRAINT pk_carts PRIMARY KEY (id)
);

CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    name text NOT NULL,
    code text,
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by bigint,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE commission_ledger_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    staff_id bigint NOT NULL,
    location_id bigint NOT NULL,
    transaction_id bigint NOT NULL,
    sale_line_id bigint NOT NULL,
    product_id bigint NOT NULL,
    stock_code_snapshot character varying(30) NOT NULL,
    department_id bigint,
    commission_rule_id bigint,
    commission_type character varying(20) NOT NULL,
    rate_applied numeric(9,4) NOT NULL,
    line_net numeric(19,2) NOT NULL,
    line_cost numeric(19,3) NOT NULL,
    quantity numeric(18,4) NOT NULL,
    amount numeric(19,2) NOT NULL,
    was_capped boolean NOT NULL,
    business_date date NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_commission_ledger_entries PRIMARY KEY (id)
);

CREATE TABLE commission_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    staff_id bigint NOT NULL,
    product_id bigint,
    department_id bigint,
    commission_type character varying(20) NOT NULL,
    value numeric(9,4) NOT NULL,
    max_commission numeric(19,2),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_commission_rules PRIMARY KEY (id)
);

CREATE TABLE currencies (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    name text NOT NULL,
    symbol text NOT NULL,
    scale integer NOT NULL,
    rounding integer NOT NULL,
    minimum_tender numeric NOT NULL,
    is_base_currency boolean NOT NULL,
    is_active boolean NOT NULL,
    exchange_rate numeric NOT NULL,
    exchange_rate_updated_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_currencies PRIMARY KEY (id)
);

CREATE TABLE customer_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    customer_id bigint NOT NULL,
    account_number bigint NOT NULL,
    credit_limit numeric NOT NULL,
    balance_due numeric NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_customer_accounts PRIMARY KEY (id)
);

CREATE TABLE customer_order_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    customer_order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    variant_id bigint,
    ordered_qty numeric NOT NULL,
    filled_qty numeric NOT NULL,
    unit_price numeric NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_customer_order_lines PRIMARY KEY (id)
);

CREATE TABLE customer_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    order_number bigint NOT NULL,
    customer_id bigint NOT NULL,
    location_id bigint NOT NULL,
    status integer NOT NULL,
    ordered_on date NOT NULL,
    notes text,
    staff_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_customer_orders PRIMARY KEY (id)
);

CREATE TABLE customer_pricing_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    customer_id bigint NOT NULL,
    usual_discount_pct numeric NOT NULL,
    price_level integer NOT NULL,
    exempt_tax1 boolean NOT NULL,
    exempt_tax2 boolean NOT NULL,
    reward_points integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_customer_pricing_profiles PRIMARY KEY (id)
);

CREATE TABLE customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    customer_number bigint NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    company character varying(200),
    title character varying(50),
    billing_address_line1 character varying(200),
    billing_address_line2 character varying(200),
    billing_address_city character varying(100),
    billing_address_state_or_province character varying(100),
    billing_address_postal_code character varying(20),
    billing_address_country character varying(100),
    ship_to_address_line1 character varying(200),
    ship_to_address_line2 character varying(200),
    ship_to_address_city character varying(100),
    ship_to_address_state_or_province character varying(100),
    ship_to_address_postal_code character varying(20),
    ship_to_address_country character varying(100),
    contact_phone character varying(30),
    contact_extension character varying(10),
    contact_mobile character varying(30),
    contact_fax character varying(30),
    contact_email character varying(200),
    contact_website character varying(200),
    client_type character varying(50),
    birthday date,
    notes character varying(4000),
    last_purchase_on date,
    last_mailing_on date,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by bigint,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE data_protection_keys (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    friendly_name text,
    xml text,
    CONSTRAINT pk_data_protection_keys PRIMARY KEY (id)
);

CREATE TABLE departments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(20),
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by bigint,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

CREATE TABLE drawer_ledger_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    drawer_session_id bigint NOT NULL,
    entry_type character varying(20) NOT NULL,
    amount numeric(19,4) NOT NULL,
    reason character varying(200),
    transaction_id bigint,
    staff_id bigint NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_drawer_ledger_entries PRIMARY KEY (id)
);

CREATE TABLE drawer_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    station_id bigint NOT NULL,
    location_id bigint NOT NULL,
    opened_by_staff_id bigint NOT NULL,
    closed_by_staff_id bigint,
    opening_float numeric(19,4) NOT NULL,
    status character varying(20) NOT NULL,
    business_date date NOT NULL,
    opened_at timestamp with time zone NOT NULL,
    closed_at timestamp with time zone,
    counted_cash numeric(19,4),
    expected_cash numeric(19,4) NOT NULL,
    variance numeric(19,4) NOT NULL,
    tender_totals_json text,
    department_net_sales_json text,
    net_sales numeric NOT NULL,
    tax1collected numeric(19,4) NOT NULL,
    tax2collected numeric(19,4) NOT NULL,
    cost_of_goods_sold numeric(19,4) NOT NULL,
    transaction_count integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_drawer_sessions PRIMARY KEY (id)
);

CREATE TABLE external_entity_maps (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    provider text NOT NULL,
    entity_type text NOT NULL,
    local_id bigint,
    local_key text,
    remote_id text NOT NULL,
    remote_name text,
    last_synced_at timestamp with time zone,
    content_hash text,
    row_version bigint NOT NULL,
    CONSTRAINT pk_external_entity_maps PRIMARY KEY (id)
);

CREATE TABLE fiscal_years (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    year integer NOT NULL,
    starts_on date NOT NULL,
    ends_on date NOT NULL,
    status character varying(20) NOT NULL,
    closed_at timestamp with time zone,
    closed_by bigint,
    archived_rows integer NOT NULL,
    archived_net_sales numeric(19,2) NOT NULL,
    notes character varying(500),
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_fiscal_years PRIMARY KEY (id)
);

CREATE TABLE gift_cards (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    serial_number text NOT NULL,
    original_value numeric NOT NULL,
    remaining_value numeric NOT NULL,
    issued_to_customer_id bigint,
    issued_on date NOT NULL,
    expires_on date,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_gift_cards PRIMARY KEY (id)
);

CREATE TABLE gift_certificates (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    serial_number text NOT NULL,
    original_value numeric NOT NULL,
    remaining_value numeric NOT NULL,
    issued_to_customer_id bigint,
    issued_on date NOT NULL,
    expires_on date,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_gift_certificates PRIMARY KEY (id)
);

CREATE TABLE invoice_payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    invoice_id bigint NOT NULL,
    amount numeric NOT NULL,
    applied_to_penalty numeric NOT NULL,
    applied_to_principal numeric NOT NULL,
    tender_type_id bigint NOT NULL,
    paid_on date NOT NULL,
    was_distributed boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_invoice_payments PRIMARY KEY (id)
);

CREATE TABLE invoices (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    invoice_number bigint NOT NULL,
    customer_id bigint NOT NULL,
    transaction_id bigint NOT NULL,
    issued_on date NOT NULL,
    due_on date NOT NULL,
    invoice_total numeric(19,4) NOT NULL,
    penalty_accrued numeric(19,4) NOT NULL,
    balance_due numeric(19,4) NOT NULL,
    last_payment_on date,
    status character varying(20) NOT NULL,
    staff_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_invoices PRIMARY KEY (id)
);

CREATE TABLE kit_components (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    kit_product_id bigint NOT NULL,
    component_product_id bigint NOT NULL,
    quantity numeric NOT NULL,
    reduce_stock boolean NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_kit_components PRIMARY KEY (id)
);

CREATE TABLE late_charge_policies (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    monthly_rate numeric NOT NULL,
    grace_period_days integer NOT NULL,
    is_enabled boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_late_charge_policies PRIMARY KEY (id)
);

CREATE TABLE layaway_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    layaway_id bigint NOT NULL,
    product_id bigint NOT NULL,
    variant_id bigint,
    quantity numeric NOT NULL,
    unit_price numeric NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_layaway_lines PRIMARY KEY (id)
);

CREATE TABLE layaway_payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    layaway_id bigint NOT NULL,
    amount numeric NOT NULL,
    tender_type_id bigint NOT NULL,
    paid_on date NOT NULL,
    created_at timestamp with time zone NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_layaway_payments PRIMARY KEY (id)
);

CREATE TABLE layaways (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    layaway_number bigint NOT NULL,
    customer_id bigint NOT NULL,
    location_id bigint NOT NULL,
    status integer NOT NULL,
    total numeric NOT NULL,
    amount_paid numeric NOT NULL,
    created_on date NOT NULL,
    staff_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_layaways PRIMARY KEY (id)
);

CREATE TABLE locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    legacy_code character varying(3) NOT NULL,
    address_line1 character varying(200),
    address_line2 character varying(200),
    address_city character varying(100),
    address_state_or_province character varying(100),
    address_postal_code character varying(20),
    address_country character varying(100),
    contact_phone character varying(30),
    contact_extension character varying(10),
    contact_mobile character varying(30),
    contact_fax character varying(30),
    contact_email character varying(200),
    contact_website character varying(200),
    time_zone_id character varying(50) NOT NULL,
    business_day_start time without time zone NOT NULL,
    base_currency_code character varying(3) NOT NULL,
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by bigint,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE loyalty_ledger_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    customer_id bigint NOT NULL,
    transaction_id bigint,
    entry_type integer NOT NULL,
    points integer NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_loyalty_ledger_entries PRIMARY KEY (id)
);

CREATE TABLE loyalty_policies (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    is_enabled boolean NOT NULL,
    points_per_dollar numeric NOT NULL,
    minimum_required integer NOT NULL,
    percent_enabled boolean NOT NULL,
    reward_percent numeric NOT NULL,
    fixed_enabled boolean NOT NULL,
    reward_fixed_amount numeric NOT NULL,
    suppress_if_subtotal_discount_applied boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_loyalty_policies PRIMARY KEY (id)
);

CREATE TABLE matrix_dimensions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    position integer NOT NULL,
    name text NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_matrix_dimensions PRIMARY KEY (id)
);

CREATE TABLE migration_batches (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    source_file_name character varying(260) NOT NULL,
    entity character varying(30) NOT NULL,
    source_hash character varying(64) NOT NULL,
    stage character varying(20) NOT NULL,
    rows_staged integer NOT NULL,
    rows_deleted_in_source integer NOT NULL,
    blocking_errors integer NOT NULL,
    warnings integer NOT NULL,
    rows_imported integer NOT NULL,
    rows_skipped integer NOT NULL,
    analysis_json jsonb,
    validation_json jsonb,
    reconciliation_json jsonb,
    validated_at timestamp with time zone,
    dry_run_at timestamp with time zone,
    imported_at timestamp with time zone,
    notes character varying(1000),
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_migration_batches PRIMARY KEY (id)
);

CREATE TABLE migration_staging_rows (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    batch_id bigint NOT NULL,
    row_number integer NOT NULL,
    payload_json jsonb NOT NULL,
    is_deleted_in_source boolean NOT NULL,
    legacy_key character varying(60),
    is_valid boolean,
    problems character varying(2000),
    outcome character varying(200),
    row_version bigint NOT NULL,
    CONSTRAINT pk_migration_staging_rows PRIMARY KEY (id)
);

CREATE TABLE number_sequences (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    kind character varying(30) NOT NULL,
    prefix character varying(10) NOT NULL,
    pad_width integer NOT NULL,
    next_number bigint NOT NULL,
    high_water_mark bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_number_sequences PRIMARY KEY (id)
);

CREATE TABLE "OpenIddictApplications" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    application_type character varying(50),
    client_id character varying(100),
    client_secret text,
    client_type character varying(50),
    concurrency_token character varying(50),
    consent_type character varying(50),
    display_name text,
    display_names text,
    json_web_key_set text,
    permissions text,
    post_logout_redirect_uris text,
    properties text,
    redirect_uris text,
    requirements text,
    settings text,
    CONSTRAINT pk_open_iddict_applications PRIMARY KEY (id)
);

CREATE TABLE "OpenIddictScopes" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    concurrency_token character varying(50),
    description text,
    descriptions text,
    display_name text,
    display_names text,
    name character varying(200),
    properties text,
    resources text,
    CONSTRAINT pk_open_iddict_scopes PRIMARY KEY (id)
);

CREATE TABLE permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    key character varying(60) NOT NULL,
    description character varying(200) NOT NULL,
    "group" character varying(40) NOT NULL,
    is_sensitive boolean NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE pole_display_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    station_id bigint,
    name character varying(60) NOT NULL,
    port character varying(60) NOT NULL,
    baud_rate integer NOT NULL,
    line1width integer NOT NULL,
    line2width integer NOT NULL,
    idle_line1 character varying(60) NOT NULL,
    idle_line2 character varying(60) NOT NULL,
    clear_command character varying(60) NOT NULL,
    line1command character varying(60) NOT NULL,
    line2command character varying(60) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_pole_display_profiles PRIMARY KEY (id)
);

CREATE TABLE pos_policies (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    apply_tax1 boolean NOT NULL,
    apply_tax2 boolean NOT NULL,
    allow_tax_override boolean NOT NULL,
    apply_add_on_charge boolean NOT NULL,
    fast_scan_mode boolean NOT NULL,
    auto_save_sales boolean NOT NULL,
    confirm_before_saving_sales boolean NOT NULL,
    scan_random_weight_barcodes boolean NOT NULL,
    staff_may_discount boolean NOT NULL,
    allow_item_list_edit boolean NOT NULL,
    track_staff_sales boolean NOT NULL,
    require_supervisor_to_void boolean NOT NULL,
    use_employee_time_clock boolean NOT NULL,
    print_credit_card_signature_line boolean NOT NULL,
    print_client_name_on_sales_slip boolean NOT NULL,
    carry_over_city_state_zip boolean NOT NULL,
    default_tender_type_id bigint,
    abandoned_cart_timeout_minutes integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_pos_policies PRIMARY KEY (id)
);

CREATE TABLE price_breaks (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    level integer NOT NULL,
    min_quantity numeric NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_price_breaks PRIMARY KEY (id)
);

CREATE TABLE price_quote_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    price_quote_id bigint NOT NULL,
    product_id bigint NOT NULL,
    variant_id bigint,
    quantity numeric NOT NULL,
    unit_price numeric NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_price_quote_lines PRIMARY KEY (id)
);

CREATE TABLE price_quotes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    quote_number bigint NOT NULL,
    customer_id bigint NOT NULL,
    location_id bigint NOT NULL,
    status integer NOT NULL,
    issued_on date NOT NULL,
    expires_on date,
    total numeric NOT NULL,
    staff_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_price_quotes PRIMARY KEY (id)
);

CREATE TABLE pricing_rule_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    rule_key character varying(40) NOT NULL,
    "order" integer NOT NULL,
    enabled boolean NOT NULL,
    parameters_json jsonb,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_pricing_rule_settings PRIMARY KEY (id)
);

CREATE TABLE printer_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    station_id bigint,
    name character varying(60) NOT NULL,
    setup_command character varying(120),
    cutter_command character varying(120),
    red_command character varying(120),
    black_command character varying(120),
    port character varying(120),
    default_copies integer NOT NULL,
    page_eject boolean NOT NULL,
    extra_copy_on_card boolean NOT NULL,
    initialize_serial boolean NOT NULL,
    output character varying(16) NOT NULL,
    columns integer NOT NULL,
    drawer_trigger character varying(120) NOT NULL,
    drawer_repeat integer NOT NULL,
    open_drawer_on_print boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_printer_profiles PRIMARY KEY (id)
);

CREATE TABLE product_prices (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    level integer NOT NULL,
    price numeric NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_product_prices PRIMARY KEY (id)
);

CREATE TABLE product_suppliers (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    supplier_id bigint NOT NULL,
    rank integer NOT NULL,
    cost numeric NOT NULL,
    reorder_number text,
    case_qty numeric NOT NULL,
    minimum_order_qty numeric NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_product_suppliers PRIMARY KEY (id)
);

CREATE TABLE product_variants (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    dim1value text NOT NULL,
    dim2value text,
    dim3value text,
    variant_code text NOT NULL,
    upc text,
    on_hand numeric NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_product_variants PRIMARY KEY (id)
);

CREATE TABLE products (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    stock_code character varying(30) NOT NULL,
    name character varying(200) NOT NULL,
    description text,
    type integer NOT NULL,
    upc character varying(30),
    tax1applies boolean NOT NULL,
    tax2applies boolean NOT NULL,
    regular_price numeric NOT NULL,
    last_cost numeric NOT NULL,
    avg_cost numeric NOT NULL,
    gross_margin_pct numeric NOT NULL,
    base_stock integer NOT NULL,
    reorder_point integer NOT NULL,
    reorder_qty integer NOT NULL,
    on_hand numeric NOT NULL,
    on_order numeric NOT NULL,
    case_qty numeric NOT NULL,
    ship_weight numeric NOT NULL,
    bin_location character varying(50),
    pos_message text,
    invoice_message text,
    notes text,
    has_image boolean NOT NULL,
    department_id bigint,
    category_id bigint,
    substitute_product_id bigint,
    tag_along_product_id bigint,
    parent_product_id bigint,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by bigint,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE purchase_order_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    purchase_order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    variant_id bigint,
    order_qty numeric NOT NULL,
    case_qty numeric NOT NULL,
    cost_each numeric NOT NULL,
    order_cost numeric NOT NULL,
    qty_received numeric NOT NULL,
    in_stock_at_generation numeric NOT NULL,
    on_order_at_generation numeric NOT NULL,
    back_orders numeric NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_purchase_order_lines PRIMARY KEY (id)
);

CREATE TABLE purchase_order_receipts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    purchase_order_id bigint NOT NULL,
    received_on date NOT NULL,
    freight_total numeric NOT NULL,
    staff_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_purchase_order_receipts PRIMARY KEY (id)
);

CREATE TABLE purchase_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    po_number bigint NOT NULL,
    supplier_id bigint NOT NULL,
    location_id bigint NOT NULL,
    status integer NOT NULL,
    quantity_strategy integer NOT NULL,
    header_text text,
    posted_on date,
    due_on date,
    total numeric NOT NULL,
    accounting_bill_ref text,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_purchase_orders PRIMARY KEY (id)
);

CREATE TABLE reader_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    station_id bigint,
    name character varying(60) NOT NULL,
    host character varying(120) NOT NULL,
    port integer NOT NULL,
    protocol character varying(16) NOT NULL,
    antenna_zones character varying(200) NOT NULL,
    rssi_threshold_dbm integer NOT NULL,
    minimum_read_count integer NOT NULL,
    debounce_ms integer NOT NULL,
    coalesce_ms integer NOT NULL,
    flush_interval_ms integer NOT NULL,
    max_batch_size integer NOT NULL,
    auto_accept_batches boolean NOT NULL,
    continuous_mode boolean NOT NULL,
    output_power_dbm text NOT NULL,
    region integer NOT NULL,
    frequency_start_index integer NOT NULL,
    frequency_end_index integer NOT NULL,
    link_profile integer NOT NULL,
    beeper integer NOT NULL,
    antenna_return_loss_threshold_db integer NOT NULL,
    impinj_fast_tid boolean NOT NULL,
    dense_reader_mode boolean NOT NULL,
    device_address integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_reader_profiles PRIMARY KEY (id)
);

CREATE TABLE role_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    role_id bigint NOT NULL,
    permission_key character varying(60) NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (id)
);

CREATE TABLE sale_adjustments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    transaction_id bigint NOT NULL,
    type character varying(24) NOT NULL,
    label character varying(120) NOT NULL,
    amount numeric(19,4) NOT NULL,
    serial character varying(64),
    row_version bigint NOT NULL,
    CONSTRAINT pk_sale_adjustments PRIMARY KEY (id)
);

CREATE TABLE sale_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    transaction_id bigint NOT NULL,
    sequence integer NOT NULL,
    product_id bigint NOT NULL,
    variant_id bigint,
    serialized_unit_id bigint,
    epc character varying(96),
    serial_number character varying(64),
    stock_code_snapshot character varying(24),
    name_snapshot character varying(200),
    source character varying(20) NOT NULL,
    quantity numeric(18,4) NOT NULL,
    chargeable_quantity numeric(18,4) NOT NULL,
    unit_price numeric(19,4) NOT NULL,
    discount_pct numeric(7,2) NOT NULL,
    extended_net numeric(19,4) NOT NULL,
    prorated_adjustment numeric(19,4) NOT NULL,
    taxable_net numeric(19,4) NOT NULL,
    tax1applies boolean NOT NULL,
    tax2applies boolean NOT NULL,
    tax1amount numeric(19,4) NOT NULL,
    tax2amount numeric(19,4) NOT NULL,
    unit_cost_snapshot numeric(19,3) NOT NULL,
    price_origin character varying(20) NOT NULL,
    line_type character varying(20) NOT NULL,
    returned_to_stock boolean NOT NULL,
    note character varying(500),
    row_version bigint NOT NULL,
    CONSTRAINT pk_sale_lines PRIMARY KEY (id)
);

CREATE TABLE sale_pricings (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    discount_pct numeric NOT NULL,
    starts_on date NOT NULL,
    ends_on date NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_sale_pricings PRIMARY KEY (id)
);

CREATE TABLE sale_tax_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    transaction_id bigint NOT NULL,
    tax1name character varying(40) NOT NULL,
    tax1rate numeric(9,4) NOT NULL,
    tax2name character varying(40) NOT NULL,
    tax2rate numeric(9,4) NOT NULL,
    tax2compound boolean NOT NULL,
    add_on_name character varying(40) NOT NULL,
    add_on_rate numeric(9,4) NOT NULL,
    add_on_taxable boolean NOT NULL,
    tax_inclusive boolean NOT NULL,
    tax_registration_number character varying(40),
    row_version bigint NOT NULL,
    CONSTRAINT pk_sale_tax_snapshots PRIMARY KEY (id)
);

CREATE TABLE sale_tenders (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    transaction_id bigint NOT NULL,
    tender_type_id bigint NOT NULL,
    behaviour character varying(24) NOT NULL,
    amount numeric(19,4) NOT NULL,
    amount_tendered numeric(19,4) NOT NULL,
    change_given numeric(19,4) NOT NULL,
    currency_id bigint,
    exchange_rate numeric(18,8) NOT NULL,
    reference character varying(64),
    auth_code character varying(32),
    card_last4 character varying(4),
    gateway_reference character varying(64),
    row_version bigint NOT NULL,
    CONSTRAINT pk_sale_tenders PRIMARY KEY (id)
);

CREATE TABLE sales_history_archives (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    fiscal_year_id bigint NOT NULL,
    location_id bigint NOT NULL,
    year integer NOT NULL,
    month integer NOT NULL,
    product_id bigint NOT NULL,
    stock_code_snapshot character varying(30) NOT NULL,
    name_snapshot character varying(200) NOT NULL,
    department_id bigint,
    quantity_sold numeric(18,4) NOT NULL,
    net_sales numeric(19,2) NOT NULL,
    cost_of_goods_sold numeric(19,3) NOT NULL,
    transaction_count integer NOT NULL,
    archived_at timestamp with time zone NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_sales_history_archives PRIMARY KEY (id)
);

CREATE TABLE sales_transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    transaction_number bigint NOT NULL,
    location_id bigint NOT NULL,
    station_id bigint NOT NULL,
    staff_id bigint NOT NULL,
    customer_id bigint,
    drawer_session_id bigint,
    business_date date NOT NULL,
    subtotal numeric(19,4) NOT NULL,
    discount_total numeric(19,4) NOT NULL,
    add_on_charge_total numeric(19,4) NOT NULL,
    tax1total numeric(19,4) NOT NULL,
    tax2total numeric(19,4) NOT NULL,
    grand_total numeric(19,4) NOT NULL,
    rounding_adjustment numeric NOT NULL,
    change_given numeric NOT NULL,
    cost_of_goods_sold numeric(19,4) NOT NULL,
    loyalty_points_earned integer NOT NULL,
    loyalty_points_redeemed integer NOT NULL,
    status character varying(20) NOT NULL,
    is_training boolean NOT NULL,
    voided_by_transaction_id bigint,
    reverses_transaction_id bigint,
    void_reason text,
    void_approved_by_staff_id bigint,
    invoice_id bigint,
    reprint_count integer NOT NULL,
    completed_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_sales_transactions PRIMARY KEY (id)
);

CREATE TABLE scale_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    station_id bigint,
    name character varying(60) NOT NULL,
    port character varying(60) NOT NULL,
    baud_rate integer NOT NULL,
    data_bits integer NOT NULL,
    parity character varying(16) NOT NULL,
    stop_bits character varying(16) NOT NULL,
    get_weight_command character varying(16) NOT NULL,
    zero_command character varying(16) NOT NULL,
    unit character varying(8) NOT NULL,
    timeout_ms integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_scale_profiles PRIMARY KEY (id)
);

CREATE TABLE serialized_units (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    variant_id bigint,
    serial_number character varying(64),
    epc character varying(96),
    state character varying(20) NOT NULL,
    location_id bigint NOT NULL,
    received_on timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_serialized_units PRIMARY KEY (id)
);

CREATE TABLE staff_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    staff_code character varying(8) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    pin_hash character varying(256),
    failed_pin_attempts integer NOT NULL,
    pin_locked_until timestamp with time zone,
    access_level integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_staff_profiles PRIMARY KEY (id)
);

CREATE TABLE stations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    station_code character varying(3) NOT NULL,
    location_id bigint NOT NULL,
    name character varying(100),
    fast_scan_mode boolean,
    auto_save_sales boolean,
    confirm_before_saving boolean,
    scan_random_weight_barcodes boolean,
    default_tender_type_id bigint,
    printer_profile_id bigint,
    reader_profile_id bigint,
    scale_profile_id bigint,
    pole_display_profile_id bigint,
    reader_mode character varying(16) NOT NULL,
    agent_version character varying(32),
    last_heartbeat timestamp with time zone,
    agent_token_hash character varying(128),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_stations PRIMARY KEY (id)
);

CREATE TABLE stock_count_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    stock_count_id bigint NOT NULL,
    product_id bigint NOT NULL,
    variant_id bigint,
    stock_code character varying(30) NOT NULL,
    product_name character varying(200) NOT NULL,
    counted_qty numeric(18,4) NOT NULL,
    system_qty_at_count numeric(18,4) NOT NULL,
    unit_cost numeric(19,3) NOT NULL,
    notes character varying(200),
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_stock_count_lines PRIMARY KEY (id)
);

CREATE TABLE stock_counts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    count_number bigint NOT NULL,
    location_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    notes character varying(500),
    department_id bigint,
    posted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_stock_counts PRIMARY KEY (id)
);

CREATE TABLE stock_ledger_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    variant_id bigint,
    location_id bigint NOT NULL,
    movement_type character varying(20) NOT NULL,
    quantity numeric(18,4) NOT NULL,
    unit_cost numeric(19,3) NOT NULL,
    reference_type text,
    reference_id bigint,
    reason text,
    occurred_at timestamp with time zone NOT NULL,
    staff_id bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_stock_ledger_entries PRIMARY KEY (id)
);

CREATE TABLE stock_levels (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    variant_id bigint,
    location_id bigint NOT NULL,
    on_hand numeric(18,4) NOT NULL,
    on_order numeric(18,4) NOT NULL,
    committed numeric(18,4) NOT NULL,
    last_sold_on timestamp with time zone,
    row_version bigint NOT NULL,
    CONSTRAINT pk_stock_levels PRIMARY KEY (id)
);

CREATE TABLE stock_transfer_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    stock_transfer_id bigint NOT NULL,
    product_id bigint NOT NULL,
    variant_id bigint,
    stock_code character varying(30) NOT NULL,
    product_name character varying(200) NOT NULL,
    quantity numeric(18,4) NOT NULL,
    quantity_received numeric(18,4) NOT NULL,
    unit_cost numeric(19,3) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_stock_transfer_lines PRIMARY KEY (id)
);

CREATE TABLE stock_transfers (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    transfer_number bigint NOT NULL,
    from_location_id bigint NOT NULL,
    to_location_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    notes character varying(500),
    shipped_at timestamp with time zone,
    received_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_stock_transfers PRIMARY KEY (id)
);

CREATE TABLE supervisor_approvals (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    permission character varying(60) NOT NULL,
    action character varying(120) NOT NULL,
    context character varying(500),
    requested_by_staff_id bigint NOT NULL,
    station_id bigint NOT NULL,
    location_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    approved_by_staff_id bigint,
    requested_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    answered_at timestamp with time zone,
    consumed_at timestamp with time zone,
    denial_reason character varying(500),
    row_version bigint NOT NULL,
    CONSTRAINT pk_supervisor_approvals PRIMARY KEY (id)
);

CREATE TABLE suppliers (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    supplier_number character varying(20) NOT NULL,
    company character varying(200) NOT NULL,
    contact_first_name character varying(100),
    contact_last_name character varying(100),
    title character varying(50),
    address_line1 character varying(200),
    address_line2 character varying(200),
    address_city character varying(100),
    address_state_or_province character varying(100),
    address_postal_code character varying(20),
    address_country character varying(100),
    contact_phone character varying(30),
    contact_extension character varying(10),
    contact_mobile character varying(30),
    contact_fax character varying(30),
    contact_email character varying(200),
    contact_website character varying(200),
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by bigint,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_suppliers PRIMARY KEY (id)
);

CREATE TABLE sync_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    provider text NOT NULL,
    direction integer NOT NULL,
    entity text NOT NULL,
    request_payload text,
    response_payload text,
    status integer NOT NULL,
    error_message text,
    record_count integer NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    duration_ms bigint NOT NULL,
    row_version bigint NOT NULL,
    CONSTRAINT pk_sync_logs PRIMARY KEY (id)
);

CREATE TABLE tax_configurations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    effective_from date NOT NULL,
    effective_to date,
    tax1enabled boolean NOT NULL,
    tax1name character varying(50) NOT NULL,
    tax1rate numeric(7,4) NOT NULL,
    tax2enabled boolean NOT NULL,
    tax2name character varying(50) NOT NULL,
    tax2rate numeric(7,4) NOT NULL,
    tax2compound boolean NOT NULL,
    add_on_charge_enabled boolean NOT NULL,
    add_on_charge_name character varying(50) NOT NULL,
    add_on_charge_rate numeric(7,4) NOT NULL,
    add_on_charge_taxable boolean NOT NULL,
    taxation_type character varying(20) NOT NULL,
    registration_number character varying(50),
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_tax_configurations PRIMARY KEY (id)
);

CREATE TABLE tender_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    display_name text NOT NULL,
    behaviour integer NOT NULL,
    sort_order integer NOT NULL,
    icon_key text,
    opens_cash_drawer boolean NOT NULL,
    allows_over_tender boolean NOT NULL,
    rounds_to_minimum_tender boolean NOT NULL,
    counts_towards_drawer_cash boolean NOT NULL,
    requires_reference boolean NOT NULL,
    prints_signature_copy boolean NOT NULL,
    allowed_for_refunds boolean NOT NULL,
    currency_code text,
    external_accounting_key text,
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by bigint,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_tender_types PRIMARY KEY (id)
);

CREATE TABLE time_clock_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    staff_id bigint NOT NULL,
    location_id bigint NOT NULL,
    clock_in timestamp with time zone NOT NULL,
    clock_out timestamp with time zone,
    hours_worked numeric(9,4),
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_time_clock_entries PRIMARY KEY (id)
);

CREATE TABLE "AspNetRoleClaims" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_id bigint NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT pk_asp_net_role_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_role_claims_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES "AspNetRoles" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT pk_asp_net_user_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_user_claims_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text,
    user_id bigint NOT NULL,
    CONSTRAINT pk_asp_net_user_logins PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT fk_asp_net_user_logins_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT pk_asp_net_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_asp_net_user_roles_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES "AspNetRoles" (id) ON DELETE CASCADE,
    CONSTRAINT fk_asp_net_user_roles_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    user_id bigint NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text,
    CONSTRAINT pk_asp_net_user_tokens PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT fk_asp_net_user_tokens_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE "OpenIddictAuthorizations" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    application_id bigint,
    concurrency_token character varying(50),
    creation_date timestamp with time zone,
    properties text,
    scopes text,
    status character varying(50),
    subject character varying(400),
    type character varying(50),
    CONSTRAINT pk_open_iddict_authorizations PRIMARY KEY (id),
    CONSTRAINT fk_open_iddict_authorizations_open_iddict_applications_application FOREIGN KEY (application_id) REFERENCES "OpenIddictApplications" (id)
);

CREATE TABLE product_images (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    content bytea NOT NULL,
    content_type character varying(40) NOT NULL,
    e_tag character varying(32) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_product_images PRIMARY KEY (id),
    CONSTRAINT fk_product_images_products_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE "OpenIddictTokens" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    application_id bigint,
    authorization_id bigint,
    concurrency_token character varying(50),
    creation_date timestamp with time zone,
    expiration_date timestamp with time zone,
    payload text,
    properties text,
    redemption_date timestamp with time zone,
    reference_id character varying(100),
    status character varying(50),
    subject character varying(400),
    type character varying(50),
    CONSTRAINT pk_open_iddict_tokens PRIMARY KEY (id),
    CONSTRAINT fk_open_iddict_tokens_open_iddict_applications_application_id FOREIGN KEY (application_id) REFERENCES "OpenIddictApplications" (id),
    CONSTRAINT fk_open_iddict_tokens_open_iddict_authorizations_authorization_id FOREIGN KEY (authorization_id) REFERENCES "OpenIddictAuthorizations" (id)
);

CREATE INDEX ix_asp_net_role_claims_role_id ON "AspNetRoleClaims" (role_id);

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" (normalized_name);

CREATE INDEX ix_asp_net_user_claims_user_id ON "AspNetUserClaims" (user_id);

CREATE INDEX ix_asp_net_user_logins_user_id ON "AspNetUserLogins" (user_id);

CREATE INDEX ix_asp_net_user_roles_role_id ON "AspNetUserRoles" (role_id);

CREATE INDEX "EmailIndex" ON "AspNetUsers" (normalized_email);

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" (normalized_user_name);

CREATE INDEX ix_audit_log_entries_actor_staff_id_occurred_at ON audit_log_entries (actor_staff_id, occurred_at);

CREATE INDEX ix_audit_log_entries_correlation_id ON audit_log_entries (correlation_id);

CREATE INDEX ix_audit_log_entries_entity_type_entity_id ON audit_log_entries (entity_type, entity_id);

CREATE INDEX ix_audit_log_entries_occurred_at ON audit_log_entries (occurred_at);

CREATE UNIQUE INDEX ix_business_profiles_location_id ON business_profiles (location_id);

CREATE INDEX ix_cart_adjustments_cart_id ON cart_adjustments (cart_id);

CREATE INDEX ix_cart_lines_cart_id ON cart_lines (cart_id);

CREATE UNIQUE INDEX ix_cart_tax_overrides_cart_id ON cart_tax_overrides (cart_id);

CREATE INDEX ix_carts_station_id_status ON carts (station_id, status) WHERE status = 'Active';

CREATE INDEX ix_commission_ledger_entries_location_id_business_date ON commission_ledger_entries (location_id, business_date);

CREATE INDEX ix_commission_ledger_entries_staff_id_business_date ON commission_ledger_entries (staff_id, business_date);

CREATE INDEX ix_commission_ledger_entries_transaction_id ON commission_ledger_entries (transaction_id);

CREATE INDEX ix_commission_rules_staff_id ON commission_rules (staff_id);

CREATE UNIQUE INDEX ix_commission_rules_staff_id_product_id_department_id ON commission_rules (staff_id, product_id, department_id);

CREATE UNIQUE INDEX ix_customers_location_id_customer_number ON customers (location_id, customer_number);

CREATE UNIQUE INDEX ix_departments_location_id_name ON departments (location_id, name);

CREATE INDEX ix_drawer_ledger_entries_drawer_session_id ON drawer_ledger_entries (drawer_session_id);

CREATE INDEX ix_drawer_sessions_station_id_status ON drawer_sessions (station_id, status) WHERE status = 'Open';

CREATE INDEX ix_fiscal_years_location_id_starts_on ON fiscal_years (location_id, starts_on);

CREATE UNIQUE INDEX ix_fiscal_years_location_id_year ON fiscal_years (location_id, year);

CREATE INDEX ix_invoices_customer_id_status ON invoices (customer_id, status) WHERE status = 'Open';

CREATE INDEX ix_invoices_invoice_number ON invoices (invoice_number);

CREATE UNIQUE INDEX ix_locations_legacy_code ON locations (legacy_code);

CREATE INDEX ix_migration_batches_location_id_stage ON migration_batches (location_id, stage);

CREATE INDEX ix_migration_batches_source_hash ON migration_batches (source_hash);

CREATE INDEX ix_migration_staging_rows_batch_id_legacy_key ON migration_staging_rows (batch_id, legacy_key);

CREATE INDEX ix_migration_staging_rows_batch_id_row_number ON migration_staging_rows (batch_id, row_number);

CREATE UNIQUE INDEX ix_number_sequences_location_id_kind ON number_sequences (location_id, kind);

CREATE UNIQUE INDEX ix_open_iddict_applications_client_id ON "OpenIddictApplications" (client_id);

CREATE INDEX ix_open_iddict_authorizations_application_id_status_subject_type ON "OpenIddictAuthorizations" (application_id, status, subject, type);

CREATE UNIQUE INDEX ix_open_iddict_scopes_name ON "OpenIddictScopes" (name);

CREATE INDEX ix_open_iddict_tokens_application_id_status_subject_type ON "OpenIddictTokens" (application_id, status, subject, type);

CREATE INDEX ix_open_iddict_tokens_authorization_id ON "OpenIddictTokens" (authorization_id);

CREATE UNIQUE INDEX ix_open_iddict_tokens_reference_id ON "OpenIddictTokens" (reference_id);

CREATE UNIQUE INDEX ix_permissions_key ON permissions (key);

CREATE INDEX ix_pole_display_profiles_location_id_station_id ON pole_display_profiles (location_id, station_id);

CREATE UNIQUE INDEX ix_pricing_rule_settings_location_id_rule_key ON pricing_rule_settings (location_id, rule_key);

CREATE INDEX ix_printer_profiles_location_id_station_id ON printer_profiles (location_id, station_id);

CREATE UNIQUE INDEX ix_product_images_product_id ON product_images (product_id);

CREATE UNIQUE INDEX ix_products_location_id_stock_code ON products (location_id, stock_code) WHERE NOT is_deleted;

CREATE INDEX ix_reader_profiles_location_id_station_id ON reader_profiles (location_id, station_id);

CREATE UNIQUE INDEX ix_role_permissions_role_id_permission_key ON role_permissions (role_id, permission_key);

CREATE INDEX ix_sale_adjustments_transaction_id ON sale_adjustments (transaction_id);

CREATE INDEX ix_sale_lines_product_id ON sale_lines (product_id);

CREATE INDEX ix_sale_lines_transaction_id ON sale_lines (transaction_id);

CREATE UNIQUE INDEX ix_sale_tax_snapshots_transaction_id ON sale_tax_snapshots (transaction_id);

CREATE INDEX ix_sale_tenders_transaction_id ON sale_tenders (transaction_id);

CREATE INDEX ix_sales_history_archives_fiscal_year_id ON sales_history_archives (fiscal_year_id);

CREATE UNIQUE INDEX ix_sales_history_archives_location_id_year_month_product_id ON sales_history_archives (location_id, year, month, product_id);

CREATE INDEX ix_sales_transactions_location_id_completed_at ON sales_transactions (location_id, completed_at);

CREATE INDEX ix_sales_transactions_transaction_number ON sales_transactions (transaction_number);

CREATE INDEX ix_scale_profiles_location_id_station_id ON scale_profiles (location_id, station_id);

CREATE UNIQUE INDEX ix_serialized_units_epc ON serialized_units (epc) WHERE epc IS NOT NULL;

CREATE INDEX ix_serialized_units_product_id_state ON serialized_units (product_id, state);

CREATE UNIQUE INDEX ix_staff_profiles_staff_code ON staff_profiles (staff_code);

CREATE UNIQUE INDEX ix_staff_profiles_user_id ON staff_profiles (user_id);

CREATE UNIQUE INDEX ix_stations_location_id_station_code ON stations (location_id, station_code);

CREATE INDEX ix_stock_count_lines_stock_count_id ON stock_count_lines (stock_count_id);

CREATE UNIQUE INDEX ix_stock_count_lines_stock_count_id_product_id_variant_id ON stock_count_lines (stock_count_id, product_id, variant_id);

CREATE UNIQUE INDEX ix_stock_counts_location_id_count_number ON stock_counts (location_id, count_number);

CREATE INDEX ix_stock_counts_location_id_status ON stock_counts (location_id, status);

CREATE INDEX ix_stock_ledger_entries_product_id_location_id_occurred_at ON stock_ledger_entries (product_id, location_id, occurred_at);

CREATE UNIQUE INDEX ix_stock_levels_product_id_variant_id_location_id ON stock_levels (product_id, variant_id, location_id);

CREATE INDEX ix_stock_transfer_lines_stock_transfer_id ON stock_transfer_lines (stock_transfer_id);

CREATE UNIQUE INDEX ix_stock_transfer_lines_stock_transfer_id_product_id_variant_id ON stock_transfer_lines (stock_transfer_id, product_id, variant_id);

CREATE INDEX ix_stock_transfers_from_location_id_status ON stock_transfers (from_location_id, status);

CREATE UNIQUE INDEX ix_stock_transfers_from_location_id_transfer_number ON stock_transfers (from_location_id, transfer_number);

CREATE INDEX ix_stock_transfers_to_location_id_status ON stock_transfers (to_location_id, status);

CREATE INDEX ix_supervisor_approvals_location_id_status_expires_at ON supervisor_approvals (location_id, status, expires_at);

CREATE INDEX ix_tax_configurations_location_id_effective_from ON tax_configurations (location_id DESC, effective_from DESC);

CREATE INDEX ix_time_clock_entries_location_id_clock_in ON time_clock_entries (location_id, clock_in);

CREATE INDEX ix_time_clock_entries_staff_id_clock_in ON time_clock_entries (staff_id, clock_in);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260804094134_InitialIntegerKeys', '8.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE branding_assets (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    location_id bigint NOT NULL,
    slot character varying(20) NOT NULL,
    content bytea NOT NULL,
    content_type character varying(40) NOT NULL,
    e_tag character varying(32) NOT NULL,
    opacity_pct integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    modified_at timestamp with time zone,
    modified_by bigint,
    row_version bigint NOT NULL,
    CONSTRAINT pk_branding_assets PRIMARY KEY (id),
    CONSTRAINT fk_branding_assets_locations_location_id FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_branding_assets_location_id_slot ON branding_assets (location_id, slot);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260805071030_BrandingAssets', '8.0.11');

COMMIT;

